// Generated by tools/gen-currency-kt.py from extension/src/currency.js.
// Do not edit: change the JavaScript and regenerate, or the phone apps and the
// extension will disagree about what counts as a price.
package converter.core

/** Currency tokens to ISO 4217 codes. */
val SYMBOL_TO_CODE: Map<String, String> = linkedMapOf(
    "US\$" to "USD",
    "CA\$" to "CAD",
    "C\$" to "CAD",
    "A\$" to "AUD",
    "AU\$" to "AUD",
    "HK\$" to "HKD",
    "NZ\$" to "NZD",
    "S\$" to "SGD",
    "NT\$" to "TWD",
    "R\$" to "BRL",
    "MX\$" to "MXN",
    "AR\$" to "ARS",
    "CL\$" to "CLP",
    "COL\$" to "COP",
    "U\$S" to "USD",
    "\$U" to "UYU",
    "RD\$" to "DOP",
    "B/." to "PAB",
    "S/" to "PEN",
    "₲" to "PYG",
    "Gs." to "PYG",
    "Gs" to "PYG",
    "€" to "EUR",
    "£" to "GBP",
    "¥" to "JPY",
    "₩" to "KRW",
    "₽" to "RUB",
    "рублей" to "RUB",
    "рубля" to "RUB",
    "руб." to "RUB",
    "руб" to "RUB",
    "гривен" to "UAH",
    "грн" to "UAH",
    "₴" to "UAH",
    "₸" to "KZT",
    "тг" to "KZT",
    "₾" to "GEL",
    "₺" to "TRY",
    "₹" to "INR",
    "₪" to "ILS",
    "₱" to "PHP",
    "₡" to "CRC",
    "₦" to "NGN",
    "฿" to "THB",
    "zł" to "PLN",
    "Kč" to "CZK",
    "TL" to "TRY",
    "Ft" to "HUF",
    "Rp" to "IDR",
    "RM" to "MYR",
    "дин." to "RSD",
    "дин" to "RSD",
    "₫" to "VND",
    "đ" to "VND",
    "円" to "JPY",
    "원" to "KRW",
    "บาท" to "THB",
    "Bs." to "BOB",
    "Bs" to "BOB",
    "֏" to "AMD",
    "դր." to "AMD",
    "դր" to "AMD",
    "dr" to "AMD",
    ":-" to "SEK",
    "R" to "ZAR",
    "元" to "CNY",
    "kr" to "SEK",
    "lei" to "RON",
    "Rs." to "INR",
    "Rs" to "INR",
    "\$" to "USD",
)

/** Every currency the converter knows a name for. */
val CURRENCY_CODES: List<String> = listOf(
    "AED", "AMD", "ARS", "AUD", "BGN", "BOB", "BRL", "CAD", "CHF", "CLP", "CNY", "COP", "CRC", "CUP", "CZK", "DKK", "DOP", "EGP", "EUR", "GBP", "GEL", "GTQ", "HKD", "HUF", "IDR", "ILS", "INR", "JPY", "KRW", "KZT", "MXN", "MYR", "NGN", "NOK", "NZD", "PAB", "PEN", "PHP", "PLN", "PYG", "RON", "RSD", "RUB", "SAR", "SEK", "SGD", "THB", "TRY", "TWD", "UAH", "USD", "UYU", "VES", "VND", "ZAR"
)

/** Codes that are also everyday English words, so only read in capitals. */
val CODES_NEEDING_CAPITALS: Set<String> = setOf(
    "BOB", "COP", "CUP", "GEL", "PEN", "RUB", "TRY"
)

/** Tokens too common in ordinary text to match bare: regex source, not literals. */
val TOKEN_PATTERNS: Map<String, String> = mapOf(
    "元" to "(?<![\\p{IsHan}])元(?![\\p{IsHan}])",
    "R" to "R(?=\\s?(?:\\d{1,3}[.,   ]\\d{3}|\\d+[.,]\\d{2}|\\d{3,}))",
    ":-" to "(?<=\\d):-(?![\\d)\\p{L}])",
)

/** Symbols several currencies share; pinned down by context or not at all. */
val AMBIGUOUS_SYMBOLS: Map<String, List<String>> = mapOf(
    "\$" to listOf("ARS", "CLP", "COP", "CUP", "DOP", "MXN", "PHP", "UYU", "USD", "AUD", "CAD", "HKD", "NZD", "SGD", "TWD"),
    "¥" to listOf("JPY", "CNY"),
    "kr" to listOf("SEK", "NOK", "DKK"),
    "lei" to listOf("RON"),
    "Rs" to listOf("INR"),
    "Rs." to listOf("INR"),
    "R" to listOf("ZAR"),
    "元" to listOf("CNY", "TWD"),
    ":-" to listOf("SEK", "NOK", "DKK"),
    "dr" to listOf("AMD"),
    "Bs." to listOf("BOB", "VES"),
    "Bs" to listOf("BOB", "VES"),
)

/** ISO codes that are also ordinary words or version numbers. */
val AMBIGUOUS_CODES: Map<String, List<String>> = mapOf(
    "AMD" to listOf("AMD"),
    "PHP" to listOf("PHP"),
)

/** The number grammar, with ${MINOR} already resolved. */
const val NUMBER: String = "\\d{1,3}(?:[.,   '’]\\d{3})+(?:[.,](?:\\d{1,2}|[–-]))?|\\d+(?:[.,](?:\\d{1,2}|[–-]))?"

/** Scripts that space their words, and so need their tokens fenced by letters. */
const val SPACED_SCRIPT: String = "[\\p{IsLatin}\\p{IsCyrillic}\\p{IsGreek}\\p{IsArmenian}\\p{IsHebrew}]"
